config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:show, :index]
  resources :contacts, only: [:create, :new]
  resources :waitlists, only: [:new, :create]

  post 'voice_response', to: 'messages#voice_response'

  authenticate :user, ->(u) { u.admin? } do
    mount Upmin::Engine => '/admin'
  end

  root to: 'visitors#index'
  get :charges, to: 'charges#index'
  get :privacy, to: 'visitors#privacy'
  get :terms, to: 'visitors#terms'
  get :features, to: 'visitors#features'
  get :contact, to: 'contacts#new'
  get :ping, to: 'visitors#ping'
  devise_for :users, controllers: { invitations: 'users/invitations', registrations: 'users/registrations' }
  resources :users, only: [] do
    member do
      post :show
    end
  end

  mount Koudoku::Engine, at: 'base'

  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
    post 'webhooks' => 'webhooks#create'
  end
end

app/models/post.rb
# Blog Posts
class Post < ActiveRecord::Base
  extend FriendlyId
  translates :name, :body
  validates_presence_of :name, :body
  friendly_id :name, use: :slugged
  has_attached_file :image, styles: { medium: '304x192>', large: '671x415>', thumb: '55x55>' }, default_url: '/images/blog/:style.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  scope :recent, -> { order('created_at DESC') }
end

app/controllers/posts_controller.rb
# The blog controller
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  respond_to :html

  def index
    TrackingService.new.call(current_user, User.new, 'Blog view')
    @posts = Post.recent.page(params[:page])
    respond_with(@posts)
  end

  def show
    TrackingService.new.call(current_user, @post, 'Blog post view')
    @posts = Post.recent.page(params[:page])
    respond_with(@post)
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end
end

app/views/posts/index.html.haml
#blog
  .container{style: "margin-bottom: 100px;"}
    .section_header
      %h3= link_to "#{t('buttons.blog')}", posts_path
    .pomotodo.grid.ng-scope
      .column.width-3-4
        .menu-box
          .post_content
            - if @posts.any?
              - @posts.each do |post|
                %h1
                  = link_to post.name, post_path(post)
                %abbr.timeago{:title => post.created_at.getutc.iso8601}
                  = post.created_at.to_s
                %br
                %br
                = truncate(post.body, length: 150)
                %hr{style: "margin-top: 25px;"}
              .paginator-container
                = paginate @posts
            - else
              No Results
      .column.width-1-4
        .menu-box
          .post_content
            - @posts.each do |post|
              .recent
                %p= link_to post.name, post_path(post)
              %br

app/views/posts/show.html.haml
#blog
  .container{style: "margin-bottom: 100px;"}
    .section_header
      %h3= link_to "#{t('buttons.blog')}", posts_path
    .pomotodo.grid.ng-scope
      .column.width-3-4
        .menu-box
          .post_content
            .post_content
              %h1= @post.name
              %p
                %span.date
                  %abbr.timeago{:title => @post.created_at.getutc.iso8601}
                    = @post.created_at.to_s
              %br
              %p
                = @post.body.html_safe
            %br
            %br
            .comments
              #disqus_thread

              :javascript
                var disqus_shortname = 'ashasms';
                var disqus_config = function () {
                  this.language = "#{I18n.locale}";
                };
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
      .column.width-1-4
        .menu-box
          .post_content
            - @posts.each do |post|
              .recent
                %p= link_to post.name, post_path(post)
              %br